### ISSUE TITLE
Thumbnails version not showing big image with Gatsby image

### ISSUE THREAD

**Issue by ondrejv** [michelecocuccio/simple-react-lightbox#118]
**Describe the bug**
Hi, I'm experiencing an issue with thumbnail image wrapped in an <a> tag with inner html tags like picture element or any other (gatsby image divs and picture element in my case, but figured is is broken with anything inside an a tag) - in that case, instead of big picture the small image thumbnail is shown in the lightbox.

Code which will fail can look like this:
```
<a href="/big-image.jpg">
  <div class="gatsby-image-wrapper">
    <picture>
      <source />
      <img src="/thumbnail-image.jpg" />
    </picture>
  </div>
</a>
```

**Environment**
Gatsby v2.24.91
Node v12.16.2
SRL v 3.5.2

**To Reproduce**
Demo here: https://codesandbox.io/s/simple-react-lightbox-forked-5jcdt

**Comment by michelecocuccio** [comment]
@ondrejv hello!

How are you using Gatsby image? I have tested with the Gatsby image component and the structure I am getting is different from yours. There is no `<a href="">` wrapping the gatsy-wrapper div.

This is how I implemented with Gatsby Image
```
  <Row>
    {data.allFile.edges.map((e) => (
      <Col key={e.node.id} className="bootstrap_column" lg="4">
        <Img fluid={e.node.childImageSharp.fluid} />
      </Col>
    ))}
  </Row>
```

and this is the output
![Screenshot 2021-01-11 at 16 58 10](https://user-images.githubusercontent.com/8071249/104205431-a9dd1800-542e-11eb-8bc3-81c1365f2078.png)

Please let me know

**Comment by ondrejv** [comment]
Hi @michelecocuccio, thanks for your response.
I'm wrapping Gatsby image with link on my own from performance reasons, to provide small images as thumbnails whereas big images should be loaded via your lightbox just on users's click. If you take a look at the link: https://codesandbox.io/s/simple-react-lightbox-forked-5jcdt - only allowed element is the `<img>` directly in the `<a>` wrapper. Knowing that, it would fail to load an image also in your example of Gatsby image, I suppose.

Please let me know if it makes sense.

Thanks in advance for your investigation. Much appreciated.

**Comment by michelecocuccio** [comment]
@ondrejv hello.

I have found that Gatsby has a very very odd behaviour that I wasn't ever expecting to find. I have added a small fix in version 3.5.3 which I have released. Can you try it again and let me know? Is not the best of the best but I will work on a better solution.

**Comment by ondrejv** [comment]
Thanks for the fix! We are almost there :-)
Only issue remains, that it counts with the exact class called `gatsby-image-wrapper`, but in fact, Gatsby generates this class with a gap: "` gatsby-image-wrapper`" (also in your screenshot, I posted not really precise example initially). This actually, causes the js code fails to load a big image. See the following updated demo: https://codesandbox.io/s/simple-react-lightbox-forked-5jcdt (second box).

Cheers

**Comment by michelecocuccio** [comment]
@ondrejv I did some more testing today and I had to optimise the code a little bit better as it was breaking the "normal" implementation with Gatsby. I have released a new fix with version 3.5.4. Could you please let me know? It should be fixed.

**Comment by ondrejv** [comment]
Awesome! Works like a charm :-)
Your support is excellent - that's another reason to go pro ;-)

Cheers and have a nice day.

**Comment by michelecocuccio** [comment]
@ondrejv  thank you very much. I try to do my best. Please note that I have released the fix this morning in the PRO version so make sure you are on version 1.0.7 with the PRO version which should have the fix. Let me know if the issue persist in the PRO version as the codebase is slightly different from the FREE one.

Have a great day!

**Comment by Kvintus** [comment]
> @ondrejv thank you very much. I try to do my best. Please note that I have released the fix this morning in the PRO version so make sure you are on version 1.0.7 with the PRO version which should have the fix. Let me know if the issue persist in the PRO version as the codebase is slightly different from the FREE one.
> 
> Have a great day!

Had a problem with this in December and therefore couldn't get a good score on a site. Thank you very much for fixing it. :) bought PRO immediately
