### ISSUE TITLE
Gatsby gatsby-plugin-image duplicated image

### ISSUE THREAD

**Issue by KonstantinSchuette** [michelecocuccio/simple-react-lightbox#149]
**Describe the bug**
Images are shown multiple times in the gallery. The images have the same URL so they are exact duplicates:
![Image of Yaktocat](https://i.ibb.co/TwqC8HR/Screenshot-2021-04-07-160625.png)

**Environment*
`gatsby-info --clipboard`
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.68)
  npmPackages:
    gatsby: ^2.32.3 => 2.32.12 
    gatsby-background-image: ^1.4.1 => 1.5.0 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1 
    gatsby-plugin-brotli: ^2.0.0 => 2.0.0 
    gatsby-plugin-gatsby-cloud: ^1.0.1 => 1.0.2 
    gatsby-plugin-image: ^1.0.0 => 1.2.1 
    gatsby-plugin-manifest: ^2.12.0 => 2.12.1 
    gatsby-plugin-offline: ^3.10.0 => 3.10.2 
    gatsby-plugin-postcss: ^3.7.0 => 3.7.0 
    gatsby-plugin-preact: ^4.7.0 => 4.7.0 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5 
    gatsby-plugin-sharp: ^2.14.1 => 2.14.3 
    gatsby-plugin-zopfli: ^2.0.0 => 2.0.0 
    gatsby-source-filesystem: ^2.11.0 => 2.11.1 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.1 
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

**To Reproduce**
Code:
```
import React from "react"
import { graphql, useStaticQuery } from "gatsby"
import { GatsbyImage } from "gatsby-plugin-image"

import SimpleReactLightbox from "simple-react-lightbox"
import { SRLWrapper } from "simple-react-lightbox"

const Test = () => {
  const data = useStaticQuery(graphql`
    {
      allFile(
        filter: {
          extension: { regex: "/(jpg)|(jpeg)|(png)/" }
          relativeDirectory: { eq: "images" }
        }
      ) {
        edges {
          node {
            id
            childImageSharp {
              gatsbyImageData(quality: 90, layout: FULL_WIDTH)
            }
          }
        }
      }
    }
  `)

  return (
    <SimpleReactLightbox>
      <SRLWrapper
        options={{
          settings: {
            lightboxTransitionSpeed: 0.2,
            slideTransitionSpeed: 0.2,
          },
          buttons: { showDownloadButton: false },
          caption: {
            showCaption: false,
          },
        }}
      >
        <div className="container max-w-screen-lg xl:max-w-screen-xl sm:mx-auto sm:px-6 bg-white">
          <div className="grid grid-cols-1 gap-7 sm:grid-cols-2 lg:grid-cols-3">
            {data.allFile.edges.map(edge => {
              return (
                <a href={edge.node.childImageSharp.gatsbyImageData.src}>
                  <GatsbyImage
                    image={edge.node.childImageSharp.gatsbyImageData}
                    alt=""
                    className="h-full"
                  />
                </a>
              )
            })}
          </div>
        </div>
      </SRLWrapper>
    </SimpleReactLightbox>
  )
}

export default Test
```
1. Run `gatsby develop`
2. Click on the image

Now Every image is shown twice in the gallery

**Comment by michelecocuccio** [comment]
@KonstantinSchuette hello thanks for this.
I can't reproduce the issue. 

This is how I am implementing the library with Gatsby

```
import React from 'react'
import { Container, Row, Col } from 'react-bootstrap'
import { SRLWrapper } from 'simple-react-lightbox'
import { graphql } from 'gatsby'
import Layout from '../components/layout'
import Img from 'gatsby-image'

function GalleryWithThumbs(data) {
  return (
    <Layout>
      <SRLWrapper>
        <Container>
          <Row>
            {data.data.thumbnails.edges.map((e, index) => {
              return (
                <Col
                  key={e.node.id}
                  className="bootstrap_column link_with_overlay"
                  lg="4"
                >
                  <a
                    href={
                      data.data.images.edges[index].node.childImageSharp.fluid
                        .src
                    }
                  >
                    <Img fluid={e.node.childImageSharp.fluid} />
                  </a>
                </Col>
              )
            })}
          </Row>
        </Container>
      </SRLWrapper>
    </Layout>
  )
}

export const query = graphql`
  query {
    images: allFile(
      filter: { relativeDirectory: { eq: "gallery" } }
      sort: { order: ASC, fields: name }
    ) {
      edges {
        node {
          name
          id
          relativePath
          childImageSharp {
            fluid {
              src
              tracedSVG
              aspectRatio
              originalImg
              sizes
            }
          }
        }
      }
    }
    thumbnails: allFile(
      filter: { relativeDirectory: { eq: "gallery/thumbnails" } }
      sort: { order: ASC, fields: name }
    ) {
      edges {
        node {
          name
          id
          relativePath
          childImageSharp {
            fluid {
              src
              tracedSVG
              aspectRatio
              originalImg
              sizes
            }
          }
        }
      }
    }
  }
`

export default GalleryWithThumbs
```

Could you please reproduce an example on CodeSandbox please so I can check the error?

**Comment by KonstantinSchuette** [comment]
So first of all you are using `<Img>` from the plugin `gatsby-image` which is now deprecated. You should use `gatsby-plugin-image`. So instead of using `<Img>` you use `<GatsbyImage>` and the query also changes a bit.

In my Codesandbox example I now have the following problems:

1.  An image is duplicated in the gallery
2. About 50 errors per second are printed in the console, if you try to zoom on the image in the gallery
3. Images that have not been lazyloaded (if you haven't scrolled down to them) are not listed in the gallery

What I already found out:
Many of my packages were outdated, that caused a problem trying to create a Codesandbox sample. Now I updated all of my packages but none of the problems have been fixed.

Codesandbox:
https://codesandbox.io/s/icy-monad-qe7y7

This is my first sandbox created from my local files. I wanted that `gatsby develop` will be automatically executed and show the browser output, but you need to click on `Open Browser Pane` so see it in the browser.

**Comment by KonstantinSchuette** [comment]
Nevermind, just ignore the last sentence. I fixed it. Now its working fine

**Comment by michelecocuccio** [comment]
@KonstantinSchuette thanks. I have noticed that the Gatsby plugin has changed so there might be some issues when using the new one. I will try to add a fix soon.

**Comment by michelecocuccio** [comment]
Hello @KonstantinSchuette.

I have tested the library and it works with the lates version with Gatsy Plugin Image. Please follow [this documentation](https://simple-react-lightbox.dev/documentation/with-gatsby-image) to check how I implemented the lightbox with it.

Thanks

**Comment by KonstantinSchuette** [comment]
Soo I finally found out my error. If I remove the following plugin in the gatsby-config.ts everything works fine:
```
`gatsby-plugin-preact`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: path.join(__dirname, `src`, `images`),
      },
    },
```
I also tried passing this to the `<SRLWrapper>` but it doesn't fix the bug, if the plugin is included
```
const options = {
  settings: {
    usingPreact: true,
  },
}
```

Also https://github.com/michelecocuccio/simple-react-lightbox/issues/148 gets fixed by removing this.
