### ISSUE TITLE
Cache of used images

### ISSUE THREAD

**Issue by carloscalage** [michelecocuccio/simple-react-lightbox#54]
**Describe the bug**
I'm working on a real state website and I need to show properties dynamically with their own photo galleries, so I have a mother component wich is showing all the properties and handling the logic of selection and sending the data to the another component wich is going to show the details and the gallery. I just needed a button to show the gallery, so I have the SRLWrapper on `left: -9999` and a button using `openLightbox` to show all the photos in fullscreen.

The problem is that when I see the gallery from a property and then I decide to see another property, it somehow had the earlier photos in cache, so I need to move to the second photo or even close the gallery and open again in order to update the thumbnails and the photos. 

First the problem could be because of the data still on the state, but when I close the component it clears the state and before the data is being passed to this component before it mounts, so this is not the problem.

**Environment**
I'm using a react 16.12.0 created with creat-react-app and the latest version from simple-react-lightbox

**To Reproduce**
I uploaded a video to show the problem:
https://www.youtube.com/watch?v=J6OIVcIlw1I

**Additional context**
I don't know if there is any better way that I could do that and I don't know if this is the way that your package was idealized for, but if you could give me some light on it, it'll be amazing.

**Comment by michelecocuccio** [comment]
@carloscalage hello.

I don' think this is a bug with the light-box but more the way you are using your state in React. There are few things i don't understand like: 

> so I have the SRLWrapper on left: -9999

You don't need to move away the SRLWrapper as it's always hidden as it's using React Portal. Why are you moving it on the left? 

Also how are you fetching the datas of the properties? Simple React Lightbox works with data fetching and watch if the images are changed. You can see an example from here https://simple-react-lightbox.dev/with-api/ (the same example is available on Code Sandbox). The images are in a state, so it's working as intended. 

It's really hard to check without seeing the code, but I think that's most definitely an implementation issue. I will need to look at the code to give help but check the example with the API as it's working for this case scenarios.

**Comment by carloscalage** [comment]
Hey! Sorry for bothering you again.

Yeah, I misunderstood the way Wrapper works and I was doing something very wrong. I fixed with your answer. Thanks!

I would like to leave what I was doing and how I fixed, if anyone else is having the same problem.

Resumed: I'm getting the photos from an API and I don't want this photos to be shown on the body. So I have a button wich is going to open the lightbox and reveal all the photos. The way I did was like this: 

```javascript 
<button onClick={openLightBox}>Gallery</button>

<SRLWrapper style={{ left: -9999 }}>
images.map(image => { return <img src={image.URL} alt={image.imovel_id} /> })
</SRLWrapper>
```
That was wrong, because instead of wrapping just the photos, I can wrap all the component and all the photos inside of it are going to be  shown on lightbox, when I click the button.

Futhermore I don't need to use the `<img>` tag as a Custom gallery as documented. It offers passing an array to the wrapper, although is discouraged. So that's what I'm doing: 

```javascript 
<SRLWrapper images={images}>
   <button onClick={openLightBox}>Gallery</button>
   ...
</SRLWrapper>
```

I don't know if you have any ideas to not use this passing array method, but I worked like a charm and it's not having the "cached images" problem.

Again, I'm really sorry for bothering you with a problem that I created by not reading the documentation properly.

**Comment by michelecocuccio** [comment]
@carloscalage happy you solved it your way :) you can also put the button outside the `<SRLWrapper`>, the hook works from everywhere (it has to be inside the `<SRLLightbox>` of course). I still don't get why you are offsetting the `<SRLWrapper>` to the left but hey, if it works and you are happy I am happy as well 👍

**Comment by carloscalage** [comment]
The offsetting of SRLWrapper was because it was rendering the photos on the body in that first code. I'm not using that anymore, because I'm not rendering the photos as `<img>` tags, instead I'm passing through the props with an Array 

`<SRLWrapper images={images}>`
